name: print_map
description: Simple package to print Map & Json objects with some colors and better read.
version: 2.0.0+0
repository: https://github.com/dewetbaumann/dart-print-map

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
